server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          ##search-locations: file:///Users/paul.arenas/Documents/personal/projects/config-repo/ecommerce-system
          search-locations: file:///config-repo/
  security:
    user:
      name: admin
      password: admin123

eureka:
  instance:
    hostname: config-server
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, refresh
